[project]
name = "akinator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "matplobblib>=0.3.23",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "onnx>=1.20.1",
    "pandas>=2.3.3",
    "tensorflow>=2.20.0",
    "torch>=2.10.0",
]
